### PR TITLE
eos-extra: Refresh popular apps

### PR DESCRIPTION
**Pull request by wjt**
The new list is based on a combination of:

- Apps that have "Get ____" launchers from eos-application-tools in
  eos3.8
- Metrics on popular apps
- Manual review by me and Rob McQueen
- Previous work on [prioritizing apps to preinstall][0], which was itself
  based on metrics and manual review

Some particular notes on this new list:

- We no longer feature any built-in apps. Previously, we did this
  because not all apps were shown on the desktop. Now, all apps are
  shown on the desktop, so the app center is more about discovering new
  apps to install.
- We feature popular third-party apps, measured in part by metrics, and
  particularly those which we can't pre-install. It is likely that we
  will remove the "Get ____" launchers we previously used to work around
  not being able to pre-install certain popular apps.
- We no longer feature all com.endlessm.* apps. We now feature a
  somewhat-curated selection of the more popular apps. We do not feature
  apps whose nightly ingesters are broken.
- We no longer feature all com.endlessnetwork.* apps. We feature all the
  games, plus the most popular of the reference apps.
- We feature Kolibri, a key part of our offline content strategy.

The new list is rather shorter than the old list, but it is still more
than 35 apps, which is the maximum number shown in the App Center on any
given day.

As part of reviewing this list, I implemented a small tool to turn a
list of Flatpak app IDs into the required AppStream XML.  (It is a nice
consequence of not featuring any built-in apps that we can do this,
though that was not the reason!)

One thing I do not understand is: in the flathub and eos-apps appstream,
many apps have (eg):

```
  <component type="desktop">
    <id>com.endlessm.encyclopedia.en.desktop</id>
                                    ^^^^^^^^
```

If I include the '.desktop' in this eos-extra.xml file, then the app is
NOT marked as popular. If I remove the '.desktop', as is done by this
script, then it is.  I find this deeply unsatisfactory, particularly
since I went to some length to read the primary appstream file for each
remote and determine the appstream ID by looking up the Flatpak bundle
rather than assuming it does or does not have .desktop at the end.

I've discarded the custom categories previously added here. I have to
admit that I have not reviewed them all to make sure they are present in
the upstream appdata.

I've also discarded any custom background images.

https://phabricator.endlessm.com/T30820
https://phabricator.endlessm.com/T30379
https://phabricator.endlessm.com/T30764

[0]: https://docs.google.com/spreadsheets/d/1VTuLuF2o3FOYAq69MkdNvzy5D9G6n4DeuUVv7wUtlE4/

### CODE REVIEW

**Comment by wjt** [comment]
If this PR lands we should replace https://phabricator.endlessm.com/w/software/gnome-software/featured-apps/ with a link to the new README

**Review by andrunko — APPROVED** [review]
LGTM, thanks for that, this new script/instructions will make it easier to maintain/update.

**Comment by wjt** [comment]
Oh, well, maybe it's OK.

Here's the diff between lines containing `<id>`, sorted:

```diff
--- old.txt	2020-10-20 14:56:48.117203223 +0100
+++ new.txt	2020-10-20 14:56:51.377220205 +0100
@@ -1,11 +1,5 @@
-    <id>brasero.desktop</id>
-    <id>cheese.desktop</id>
-    <id>chromium-browser.desktop</id>
     <id>com.calibre_ebook.calibre</id>
-    <id>com.dropbox.Client.desktop</id>
-    <id>com.endlessm.all_that_is_interesting.en</id>
-    <id>com.endlessm.alodita.id</id>
-    <id>com.endlessm.alodokter.id</id>
+    <id>com.dropbox.Client</id>
     <id>com.endlessm.animals.bn_BD</id>
     <id>com.endlessm.animals.en</id>
     <id>com.endlessm.animals.es_GT</id>
@@ -18,49 +12,24 @@
     <id>com.endlessm.astronomy.id</id>
     <id>com.endlessm.astronomy.pt</id>
     <id>com.endlessm.astronomy.vi</id>
-    <id>com.endlessm.bengali_curriculum.bn_BD</id>
-    <id>com.endlessm.beritagar.id</id>
     <id>com.endlessm.bible.en</id>
     <id>com.endlessm.bible.sw</id>
-    <id>com.endlessm.bibliotecas_embrapa.pt_BR</id>
     <id>com.endlessm.biology.en</id>
     <id>com.endlessm.biology.es</id>
     <id>com.endlessm.biology.id</id>
     <id>com.endlessm.biology.pt</id>
     <id>com.endlessm.biology.th</id>
     <id>com.endlessm.biology.vi</id>
-    <id>com.endlessm.bola_net.id</id>
-    <id>com.endlessm.bollywoodlife.en_IN</id>
-    <id>com.endlessm.bong_da.vi</id>
-    <id>com.endlessm.celebrities.bn_BD</id>
-    <id>com.endlessm.celebrities.en</id>
-    <id>com.endlessm.celebrities.es_GT</id>
-    <id>com.endlessm.celebrities.es</id>
-    <id>com.endlessm.celebrities.id</id>
-    <id>com.endlessm.celebrities.pt</id>
-    <id>com.endlessm.celebrities.th</id>
-    <id>com.endlessm.celebrities.vi</id>
-    <id>com.endlessm.childrens_collection.es</id>
-    <id>com.endlessm.chinese_curriculum_english.zh_CN</id>
-    <id>com.endlessm.chinese_curriculum_math.zh_CN</id>
     <id>com.endlessm.cooking.ar</id>
     <id>com.endlessm.cooking.bn_BD</id>
     <id>com.endlessm.cooking.en</id>
     <id>com.endlessm.cooking.es_GT</id>
     <id>com.endlessm.cooking.es</id>
     <id>com.endlessm.cooking.pt</id>
-    <id>com.endlessm.creativity_center.es</id>
-    <id>com.endlessm.cricbuzz.en</id>
-    <id>com.endlessm.detik_news.id</id>
-    <id>com.endlessm.diah_didis.id</id>
-    <id>com.endlessm.dianarikasari.id</id>
     <id>com.endlessm.dinosaurs.en</id>
     <id>com.endlessm.dinosaurs.es</id>
     <id>com.endlessm.dinosaurs.pt</id>
     <id>com.endlessm.dinosaurs.vi</id>
-    <id>com.endlessm.disabilities.en</id>
-    <id>com.endlessm.disabilities.es</id>
-    <id>com.endlessm.edu_collections.es_GT</id>
     <id>com.endlessm.encyclopedia.ar</id>
     <id>com.endlessm.encyclopedia.en</id>
     <id>com.endlessm.encyclopedia.es</id>
@@ -71,32 +40,10 @@
     <id>com.endlessm.encyclopedia.sw</id>
     <id>com.endlessm.encyclopedia.th</id>
     <id>com.endlessm.encyclopedia.vi</id>
-    <id>com.endlessm.extra.pt_BR</id>
-    <id>com.endlessm.farming.bn_BD</id>
-    <id>com.endlessm.farming.en</id>
-    <id>com.endlessm.farming.es_GT</id>
-    <id>com.endlessm.farming.pt</id>
-    <id>com.endlessm.farming.vi</id>
     <id>com.endlessm.finance</id>
-    <id>com.endlessm.geography.bn_BD</id>
-    <id>com.endlessm.geography.en</id>
-    <id>com.endlessm.geography.es_GT</id>
-    <id>com.endlessm.geography.es</id>
-    <id>com.endlessm.geography.id</id>
-    <id>com.endlessm.geography.pt</id>
-    <id>com.endlessm.geography.th</id>
-    <id>com.endlessm.geography.vi</id>
-    <id>com.endlessm.girl_eat_world.en</id>
-    <id>com.endlessm.gordelicias.pt_BR</id>
-    <id>com.endlessm.green_curriculum.en</id>
-    <id>com.endlessm.guatemala.es_GT</id>
-    <id>com.endlessm.handicrafts.es</id>
     <id>com.endlessm.health.ar</id>
     <id>com.endlessm.health.en</id>
     <id>com.endlessm.health.es</id>
-    <id>com.endlessm.healthy_teeth.en</id>
-    <id>com.endlessm.healthy_teeth.es</id>
-    <id>com.endlessm.hipwee.id</id>
     <id>com.endlessm.history.bn_BD</id>
     <id>com.endlessm.history.en</id>
     <id>com.endlessm.history.es_GT</id>
@@ -109,65 +56,15 @@
     <id>com.endlessm.howto.es</id>
     <id>com.endlessm.howto.pt</id>
     <id>com.endlessm.ingles_con_rodrigo.es</id>
-    <id>com.endlessm.inibudi_profesi.id</id>
-    <id>com.endlessm.inibudi_sd.id</id>
-    <id>com.endlessm.inibudi_sma.id</id>
-    <id>com.endlessm.inibudi_smp.id</id>
-    <id>com.endlessm.inquirer.en_PH</id>
-    <id>com.endlessm.iqro.id</id>
-    <id>com.endlessm.just_lia.pt</id>
-    <id>com.endlessm.kapan_lagi.id</id>
-    <id>com.endlessm.khaosod_english.th</id>
-    <id>com.endlessm.khaosod.th</id>
-    <id>com.endlessm.library.pt</id>
-    <id>com.endlessm.mamomomomo.th</id>
-    <id>com.endlessm.manila_times.en_PH</id>
-    <id>com.endlessm.marie_therese.fr</id>
-    <id>com.endlessm.marischkaprudence.id</id>
-    <id>com.endlessm.maternity.en</id>
-    <id>com.endlessm.maternity.es</id>
     <id>com.endlessm.math.en</id>
     <id>com.endlessm.math.es</id>
     <id>com.endlessm.math.pt</id>
     <id>com.endlessm.math.vi</id>
-    <id>com.endlessm.matichon.th</id>
-    <id>com.endlessm.mayan_languages.es_GT</id>
-    <id>com.endlessm.microenterprises.es_GT</id>
-    <id>com.endlessm.mpower_agriculture.bn_BD</id>
-    <id>com.endlessm.mpower_citizen_services.bn_BD</id>
-    <id>com.endlessm.mpower_health.bn_BD</id>
-    <id>com.endlessm.mpower_law_and_rights.bn_BD</id>
     <id>com.endlessm.myths.en</id>
     <id>com.endlessm.myths.es</id>
     <id>com.endlessm.myths.pt</id>
-    <id>com.endlessm.nature_is_speaking.en</id>
-    <id>com.endlessm.ndtv_sports.en_IN</id>
-    <id>com.endlessm.okezone.id</id>
-    <id>com.endlessm.pergidulu.id</id>
-    <id>com.endlessm.phu_nu.vi</id>
-    <id>com.endlessm.physics.en</id>
-    <id>com.endlessm.physics.es</id>
-    <id>com.endlessm.physics.id</id>
-    <id>com.endlessm.physics.pt</id>
-    <id>com.endlessm.physics.vi</id>
-    <id>com.endlessm.pobpad.th</id>
-    <id>com.endlessm.prensa_libre.es_GT</id>
-    <id>com.endlessm.primer.en_PH</id>
-    <id>com.endlessm.programming_guide.en</id>
-    <id>com.endlessm.programming_guide.es</id>
-    <id>com.endlessm.programming</id>
-    <id>com.endlessm.quote_of_the_day.en</id>
-    <id>com.endlessm.rappler.en_PH</id>
+    <id>com.endlessm.photos</id>
     <id>com.endlessm.resume</id>
-    <id>com.endlessm.soccer.bn_BD</id>
-    <id>com.endlessm.soccer.en</id>
-    <id>com.endlessm.soccer.es_GT</id>
-    <id>com.endlessm.soccer.es</id>
-    <id>com.endlessm.soccer.id</id>
-    <id>com.endlessm.soccer.pt</id>
-    <id>com.endlessm.soccer.th</id>
-    <id>com.endlessm.soccer.vi</id>
-    <id>com.endlessm.social_enterprises.es_GT</id>
     <id>com.endlessm.socialsciences.en</id>
     <id>com.endlessm.socialsciences.es_GT</id>
     <id>com.endlessm.socialsciences.es</id>
@@ -175,89 +72,54 @@
     <id>com.endlessm.socialsciences.pt</id>
     <id>com.endlessm.socialsciences.th</id>
     <id>com.endlessm.socialsciences.vi</id>
-    <id>com.endlessm.textbooks.en</id>
-    <id>com.endlessm.thai_rath.th</id>
-    <id>com.endlessm.thanh_nien.vi</id>
-    <id>com.endlessm.times_of_india.en_IN</id>
-    <id>com.endlessm.translation</id>
     <id>com.endlessm.travel.bn_BD</id>
     <id>com.endlessm.travel.en</id>
     <id>com.endlessm.travel.es_GT</id>
     <id>com.endlessm.travel.es</id>
     <id>com.endlessm.travel.pt</id>
     <id>com.endlessm.ubongo_kids_demo</id>
-    <id>com.endlessm.uefa.en</id>
     <id>com.endlessm.video_animal_kingdom</id>
     <id>com.endlessm.video_animations</id>
     <id>com.endlessm.video_kids</id>
     <id>com.endlessm.video_movement</id>
-    <id>com.endlessm.vroom.en</id>
-    <id>com.endlessm.vroom.es</id>
-    <id>com.endlessm.vtv.vi</id>
-    <id>com.endlessm.water_and_sanitation.en</id>
-    <id>com.endlessm.water_and_sanitation.es</id>
-    <id>com.endlessm.wiki_art.en</id>
-    <id>com.endlessm.word_of_the_day.en</id>
     <id>com.endlessm.world_literature.en</id>
     <id>com.endlessm.world_literature.es</id>
-    <id>com.endlessm.wowshack.id</id>
-    <id>com.endlessm.your_health.pt_BR</id>
-    <id>com.endlessnetwork.arduinoprojects</id>
-    <id>com.endlessnetwork.blendertutorials</id>
-    <id>com.endlessnetwork.csstutorials</id>
-    <id>com.endlessnetwork.drawingtutorials</id>
-    <id>com.endlessnetwork.guitartutorials</id>
+    <id>com.endlessnetwork.aqueducts</id>
+    <id>com.endlessnetwork.dragonsapprentice</id>
+    <id>com.endlessnetwork.fablemaker</id>
+    <id>com.endlessnetwork.frogsquash</id>
     <id>com.endlessnetwork.htmltutorials</id>
-    <id>com.endlessnetwork.raspberrypiprojects</id>
+    <id>com.endlessnetwork.MidnightmareTeddy</id>
+    <id>com.endlessnetwork.missilemath</id>
+    <id>com.endlessnetwork.passage</id>
     <id>com.endlessnetwork.sciencesnacks</id>
     <id>com.endlessnetwork.shortfilms</id>
-    <id>com.endlessnetwork.videogamestutorials</id>
-    <id>com.github.labyrinth_team.labyrinth.desktop</id>
+    <id>com.endlessnetwork.tankwarriors</id>
+    <id>com.endlessnetwork.whitehouse</id>
     <id>com.google.Chrome</id>
-    <id>com.skype.Client.desktop</id>
+    <id>com.hack_computer.Clubhouse</id>
+    <id>com.microsoft.Teams</id>
+    <id>com.skype.Client</id>
+    <id>com.spotify.Client</id>
     <id>com.transmissionbt.Transmission</id>
-    <id>com.tux4kids.tuxmath.desktop</id>
-    <id>com.tux4kids.tuxtype.desktop</id>
+    <id>com.tux4kids.tuxmath</id>
+    <id>com.tux4kids.tuxtype</id>
+    <id>com.unity.UnityHub</id>
     <id>com.valvesoftware.Steam</id>
-    <id>edu.mit.Scratch.desktop</id>
-    <id>evolution.desktop</id>
-    <id>gnome-calculator.desktop</id>
-    <id>gnome-control-center.desktop</id>
-    <id>io.github.mmstick.FontFinder</id>
-    <id>io.thp.numptyphysics.desktop</id>
-    <id>libreoffice-calc.desktop</id>
-    <id>libreoffice-impress.desktop</id>
-    <id>libreoffice-writer.desktop</id>
+    <id>edu.mit.Scratch</id>
+    <id>io.thp.numptyphysics</id>
     <id>net.minetest.Minetest</id>
     <id>net.scribus.Scribus</id>
     <id>org.audacityteam.Audacity</id>
+    <id>org.blender.Blender</id>
     <id>org.gimp.GIMP</id>
-    <id>org.gnome.Chess</id>
-    <id>org.gnome.gedit.desktop</id>
-    <id>org.gnome.Genius.desktop</id>
-    <id>org.gnome.Gnote.desktop</id>
-    <id>org.gnome.Nautilus.desktop</id>
-    <id>org.gnome.Screenshot.desktop</id>
-    <id>org.gnome.SwellFoop</id>
-    <id>org.gnome.Terminal.desktop</id>
-    <id>org.gnome.Totem.desktop</id>
+    <id>org.gnome.Builder</id>
     <id>org.inkscape.Inkscape</id>
-    <id>org.kde.gcompris.desktop</id>
     <id>org.kde.gcompris</id>
-    <id>org.kde.katomic.desktop</id>
-    <id>org.kde.khangman.desktop</id>
     <id>org.kde.krita</id>
-    <id>org.laptop.TurtleArtActivity.desktop</id>
-    <id>org.libreoffice.LibreOffice</id>
+    <id>org.kde.ktuberling</id>
+    <id>org.laptop.TurtleArtActivity</id>
     <id>org.mozilla.firefox</id>
-    <id>org.openscad.OpenSCAD.desktop</id>
-    <id>org.squeakland.Etoys.desktop</id>
-    <id>org.telegram.desktop</id>
     <id>org.tuxpaint.Tuxpaint</id>
     <id>org.videolan.VLC</id>
-    <id>rhythmbox.desktop</id>
-    <id>shotwell.desktop</id>
-    <id>simple-scan.desktop</id>
     <id>us.zoom.Zoom</id>
-    <id>vinagre.desktop</id>
-    <id>yelp.desktop</id>
```

So, some of the apps that used to have `.desktop` suffixed will have it removed by this PR (Dropbox, Skype pop out at me). I can't explain why the ids in this file need to be *wrong* for them to show up (Dropbox in the Flathub appstream has `<id>com.dropbox.Client.desktop</id>`) but it does appear to be true.

**Comment by andrunko** [comment]
Still lgtm, leaving unmerged in case you are still planning some other change.

**Pull request merged**
