### PR TITLE
pwa-metainfo-generator: Check for OGP values

### PR DESCRIPTION
**Pull request by MichaelDrydenEndless**
Added functionality to check for and apply OGP values to name, summary, or description fields if missing from the yaml file.

https://phabricator.endlessm.com/T34515

### CODE REVIEW

**Review by dbnicholson — CHANGES_REQUESTED** [review]
This looks good, but I think we have to change the name handling. If you prefer, you can punt on handling `site_name` right now.

The other two comments are just style nitpicks.

**Comment by dbnicholson** [comment]
Oh, and I think you should try to keep the changes in a single commit by [amending your commit](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit). Logically the incremental changes you're making from this review still fall under the commit's goal of adding support for OpenGraph values. In the best case, the changes you make from my review are not that interesting to the merged history. In the worst case, we'll merge something that has a series of commits where some commits are broken and only the last one works correctly. Some people feel differently about that, but at Endless we tend to follow the model that we want the merged commits to each be valid without the incremental changes from the review.

**Comment by dbnicholson** [comment]
> Oh, and I think you should try to keep the changes in a single commit by [amending your commit](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit). Logically the incremental changes you're making from this review still fall under the commit's goal of adding support for OpenGraph values. In the best case, the changes you make from my review are not that interesting to the merged history. In the worst case, we'll merge something that has a series of commits where some commits are broken and only the last one works correctly. Some people feel differently about that, but at Endless we tend to follow the model that we want the merged commits to each be valid without the incremental changes from the review.

https://github.blog/2022-06-30-write-better-commits-build-better-projects/ does a better job of explaining this than I'm doing. Don't worry if you don't quite get it at first or don't quite know how to do what it's suggesting.

**Comment by MichaelDrydenEndless** [comment]
I ammended that commit (and pushed another one adding keyword retrieval from the header). Sorry about the whitespace stuff, I tend to space code out as im working on it to make it a bit easier to read. I'll make sure to fix the any whitespace I mess with.

**Comment by dbnicholson** [comment]
> I ammended that commit (and pushed another one adding keyword retrieval from the header). Sorry about the whitespace stuff, I tend to space code out as im working on it to make it a bit easier to read. I'll make sure to fix the any whitespace I mess with.

That looks good. I agree on the use of whitespace so that logical blocks are separated. I don't want to get too hung up on it (it's mostly in the eye of the beholder), but in those 2 cases I think it was doing the opposite.

**Comment by dbnicholson** [comment]
> > I ammended that commit (and pushed another one adding keyword retrieval from the header). Sorry about the whitespace stuff, I tend to space code out as im working on it to make it a bit easier to read. I'll make sure to fix the any whitespace I mess with.
> 
> That looks good. I agree on the use of whitespace so that logical blocks are separated. I don't want to get too hung up on it (it's mostly in the eye of the beholder), but in those 2 cases I think it was doing the opposite.

I forgot to tell you that really the best way to check the style for python scripts is to use the `flake8` tool. You can install it with `apt install flake8`. There's already configuration wired up here so you can just run `flake8` and it will tell you if there are any style issues. For example, it likes 2 lines between functions, so that's what we do :)

After #36, this will happen automatically for PRs. In the meantime, I fixed up the issues and will merge them.

**Review by dbnicholson — APPROVED** [review]

**Pull request merged**
